services:
  webpage:
    build: .
    image: webpage:latest
    container_name: webpage
    expose:
      - 80
    networks:
      - webproxy
    restart: always

networks:
  webproxy:
    name: webproxy
    external: true
