version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: homepage_production_django
    container_name: homepage_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    expose:
      - 5000
    command: /start
    restart: always
    networks:
      - default
      - webproxy

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: homepage_production_postgres
    container_name: homepage_db
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  redis:
    image: redis:5.0
    container_name: homepage_redis
    restart: always

networks:
  webproxy:
    name: webproxy
    external: true
